import type { Metadata } from "next";
import "./globals.css";
import TanstackProvider from "@/providers/TanstackProvider";
import {Provider} from 'react-redux'
import { store } from "@/redux/store";
import ReduxProvider from "@/ReduxProvider";

export const metadata: Metadata = {
  title: "Chat app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
      >
        <TanstackProvider>
          <ReduxProvider> {children}</ReduxProvider>
        </TanstackProvider>
      </body>
    </html>
  );
}
